name: Fetch new data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"   # <=== Change this value

jobs:
  fetch-new-data:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install node deps
        run: |
          npm install
          npx cypress install
      - name: run cypress
        run: |
          npx cypress run --browser chrome
        env:
          CYPRESS_STREET: ${{ vars.STREET }}
          CYPRESS_HOUSENUM: ${{ vars.HOUSENUM }}
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
      - name: push to main
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: main
          commit_message: 'Auto update calendar'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: update readme permalinks
        run: |
          echo "https://github.com/stubduffy/waste-when/blob/$(git rev-parse HEAD)/cal.json#L1-L6" > README.md
      - name: push to main
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: main
          commit_message: 'Auto update readme'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 