name: Notify

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"   # <=== Change this value

jobs:
  notify:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: install Python dependencies
        run: pip3 install -r requirements.txt

      - name: run tests
        run: |
          python3 sms.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACESS_KEY: ${{ secrets.AWS_SECRET_ACESS_KEY }}
          PHONE: ${{ secrets.phone }}